# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'GTravel_HyBird' do
#  use_frameworks!
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Alamofire', '~> 4.7.1'
  pod 'SnapKit', '~> 4.0.0'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
    'ART',
	'RCTLinkingIOS',
	'RCTActionSheet',
	'RCTVibration',
	'RCTGeolocation',
	'RCTCameraRoll',
	'RCTSettings',
    #Add any other subspecs you want to use in your project.
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  #Some lirbraries
  pod 'RNVectorIcons', :podspec => '../node_modules/react-native-vector-icons/RNVectorIcons.podspec'
end

def fix_cplusplus_header_compiler_error
	filepath = '../node_modules/react-native/React/Base/Surface/SurfaceHostingView/RCTSurfaceSizeMeasureMode.h'

	contents = []

	file = File.open(filepath, 'r')
	file.each_line do | line |
		contents << line
	end
	file.close

	if contents[32].include? "&"
		contents.insert(26, "#ifdef __cplusplus")
		contents[36] = "#endif"

		file = File.open(filepath, 'w') do |f|
			f.puts(contents)
		end
	end
end

def fix_unused_yoga_headers
	filepath = './Pods/Target Support Files/yoga/yoga-umbrella.h'

	contents = []

	file = File.open(filepath, 'r')
	file.each_line do | line |
		contents << line
	end
	file.close

	if contents[12].include? "Utils.h"
		contents.delete_at(15) # #import "YGNode.h"
		contents.delete_at(15) # #import "YGNodePrint.h"
		contents.delete_at(15) # #import "Yoga-internal.h"
		contents.delete_at(12) # #import "Utils.h"

		file = File.open(filepath, 'w') do |f|
			f.puts(contents)
		end
	end
end

def react_native_fix
	fix_cplusplus_header_compiler_error
	fix_unused_yoga_headers
end

post_install do |installer|
	react_native_fix
end
